"""
Exploratory Data Analysis for the fraud transaction dataset.

Produces:
  - docs/eda_report.md      (human-readable findings)
  - assets/*.png            (key charts)
  - data/processed/eda_summary.json (machine-readable stats, used by tests)

Usage:
    python -m src.data.eda --input data/raw/transactions.csv
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)-8s | %(message)s")
logger = logging.getLogger(__name__)


def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["timestamp"])
    logger.info("Loaded %d rows, %d columns from %s", len(df), df.shape[1], path)
    return df


def profile_dataset(df: pd.DataFrame) -> dict:
    """Compute summary statistics used both for the report and for automated tests."""
    fraud = df[df["is_fraud"] == 1]
    legit = df[df["is_fraud"] == 0]

    summary = {
        "n_rows": int(len(df)),
        "n_columns": int(df.shape[1]),
        "n_missing_values": int(df.isna().sum().sum()),
        "fraud_rate_pct": round(float(df["is_fraud"].mean() * 100), 4),
        "n_fraud": int(fraud.shape[0]),
        "n_legit": int(legit.shape[0]),
        "amount_stats": {
            "overall_mean": round(float(df["amount"].mean()), 2),
            "fraud_mean": round(float(fraud["amount"].mean()), 2),
            "legit_mean": round(float(legit["amount"].mean()), 2),
            "overall_median": round(float(df["amount"].median()), 2),
        },
        "night_txn_fraud_rate_pct": round(
            float(df[df["is_night_transaction"] == 1]["is_fraud"].mean() * 100), 3
        ),
        "day_txn_fraud_rate_pct": round(
            float(df[df["is_night_transaction"] == 0]["is_fraud"].mean() * 100), 3
        ),
        "foreign_txn_fraud_rate_pct": round(
            float(df[df["is_foreign_country"] == 1]["is_fraud"].mean() * 100), 3
        ),
        "domestic_txn_fraud_rate_pct": round(
            float(df[df["is_foreign_country"] == 0]["is_fraud"].mean() * 100), 3
        ),
        "fraud_rate_by_merchant_category": {
            k: round(float(v) * 100, 3)
            for k, v in df.groupby("merchant_category")["is_fraud"]
            .mean()
            .sort_values(ascending=False)
            .items()
        },
        "duplicate_transaction_ids": int(df["transaction_id"].duplicated().sum()),
    }
    return summary


def plot_fraud_by_hour(df: pd.DataFrame, out_path: Path) -> None:
    df = df.copy()
    df["hour"] = df["timestamp"].dt.hour
    rate_by_hour = df.groupby("hour")["is_fraud"].mean() * 100

    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.bar(rate_by_hour.index, rate_by_hour.values, color="#c0392b")
    ax.set_xlabel("Hour of Day")
    ax.set_ylabel("Fraud Rate (%)")
    ax.set_title("Fraud Rate by Hour of Day")
    ax.set_xticks(range(0, 24, 2))
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_fraud_by_category(df: pd.DataFrame, out_path: Path) -> None:
    rate = (df.groupby("merchant_category")["is_fraud"].mean() * 100).sort_values()
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.barh(rate.index, rate.values, color="#2980b9")
    ax.set_xlabel("Fraud Rate (%)")
    ax.set_title("Fraud Rate by Merchant Category")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_amount_distribution(df: pd.DataFrame, out_path: Path) -> None:
    fig, ax = plt.subplots(figsize=(8, 4.5))
    ax.hist(
        np.log1p(df[df["is_fraud"] == 0]["amount"]),
        bins=60,
        alpha=0.6,
        label="Legit",
        color="#27ae60",
    )
    ax.hist(
        np.log1p(df[df["is_fraud"] == 1]["amount"]),
        bins=60,
        alpha=0.6,
        label="Fraud",
        color="#c0392b",
    )
    ax.set_xlabel("log(1 + amount)")
    ax.set_ylabel("Count")
    ax.set_title("Transaction Amount Distribution: Fraud vs Legit")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def write_markdown_report(summary: dict, out_path: Path) -> None:
    lines = [
        "# Exploratory Data Analysis Report",
        "",
        "> Auto-generated by `src/data/eda.py`. Dataset is synthetic (see data provenance note "
        "in `src/data/generate_data.py`) but modeled on real-world fraud analytics distributions.",
        "",
        "## Dataset Overview",
        f"- Rows: **{summary['n_rows']:,}**",
        f"- Columns: **{summary['n_columns']}**",
        f"- Missing values: **{summary['n_missing_values']}**",
        f"- Duplicate transaction IDs: **{summary['duplicate_transaction_ids']}**",
        f"- Overall fraud rate: **{summary['fraud_rate_pct']}%** "
        f"({summary['n_fraud']:,} fraud / {summary['n_legit']:,} legit)",
        "",
        "## Key Findings",
        f"1. **Class imbalance is severe** — only {summary['fraud_rate_pct']}% of transactions are "
        "fraudulent, meaning accuracy is a misleading metric; the modeling stage uses "
        "PR-AUC, recall, and F1 instead.",
        f"2. **Night-time transactions are riskier**: {summary['night_txn_fraud_rate_pct']}% fraud rate "
        f"overnight vs. {summary['day_txn_fraud_rate_pct']}% during the day.",
        f"3. **Foreign transactions carry far higher risk**: {summary['foreign_txn_fraud_rate_pct']}% "
        f"vs {summary['domestic_txn_fraud_rate_pct']}% domestic.",
        f"4. **Amount patterns differ**: fraudulent transactions average "
        f"${summary['amount_stats']['fraud_mean']} vs ${summary['amount_stats']['legit_mean']} for "
        "legitimate ones.",
        "5. **Merchant category is a strong signal** — see `fraud_rate_by_merchant_category` below "
        "and `assets/fraud_by_category.png`.",
        "",
        "## Fraud Rate by Merchant Category",
        "| Category | Fraud Rate |",
        "|---|---|",
    ]
    for cat, rate in summary["fraud_rate_by_merchant_category"].items():
        lines.append(f"| {cat} | {rate}% |")

    lines += [
        "",
        "## Charts",
        "![Fraud by hour](../assets/fraud_by_hour.png)",
        "![Fraud by category](../assets/fraud_by_category.png)",
        "![Amount distribution](../assets/amount_distribution.png)",
        "",
        "## Data Quality Checks",
        f"- No missing values: {'PASS' if summary['n_missing_values'] == 0 else 'FAIL'}",
        f"- No duplicate transaction IDs: {'PASS' if summary['duplicate_transaction_ids'] == 0 else 'FAIL'}",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Run EDA on the fraud transaction dataset")
    parser.add_argument("--input", type=str, default="data/raw/transactions.csv")
    parser.add_argument("--assets-dir", type=str, default="assets")
    parser.add_argument("--docs-dir", type=str, default="docs")
    parser.add_argument("--processed-dir", type=str, default="data/processed")
    args = parser.parse_args()

    df = load_data(args.input)
    summary = profile_dataset(df)

    assets_dir = Path(args.assets_dir)
    docs_dir = Path(args.docs_dir)
    processed_dir = Path(args.processed_dir)
    for d in (assets_dir, docs_dir, processed_dir):
        d.mkdir(parents=True, exist_ok=True)

    plot_fraud_by_hour(df, assets_dir / "fraud_by_hour.png")
    plot_fraud_by_category(df, assets_dir / "fraud_by_category.png")
    plot_amount_distribution(df, assets_dir / "amount_distribution.png")

    write_markdown_report(summary, docs_dir / "eda_report.md")
    with open(processed_dir / "eda_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    logger.info("EDA complete. Report: %s", docs_dir / "eda_report.md")
    logger.info("Summary: %s", json.dumps(summary, indent=2)[:500])


if __name__ == "__main__":
    main()
